steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ann-index-base', '.', '-f', 'Dockerfile' ]
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ann-index-base']
images:
  - 'gcr.io/$PROJECT_ID/ann-index-base'
