steps:
  # Retrieve the exported model by the training
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ '-m', 'cp', '-r', '${_EXPORT_BUCKET}', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/recsys/tf-predict', '.', '-f', 'Dockerfile' ]
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/recsys/tf-predict']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tf-rec-predict'
      - '--image=gcr.io/$PROJECT_ID/recsys/tf-predict'
      - '--region=asia-east1'
      - '--port=8501'
      - '--memory=2Gi'
      - '--platform=managed'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/recsys/tf-predict'
substitutions:
    _EXPORT_BUCKET: gs://udn-news-recserve/PredictData/test/vae/model